name: Setup

inputs:
  api_key:
    description: "API Key"
    required: true

runs:
  using: composite
  steps:
    # マスクする
    echo "::add-mask::${{ inputs.apiKey }}"
      
    # ローカルプロパティの設定
    - name: Set local.properties
      env:
        API_KEY: ${{ inputs.API_KEY }}
      run: |
        echo "apiKey=${{env.API_KEY}}" >> ./local.properties

    # JDKセットアップ
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
        cache: gradle

    # Gradleセットアップ
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3