name: Setup
description: "Setup Java and Gradle environment."

inputs:
  api_key:
    description: "API Key"
    required: true

runs:
  using: composite
  steps:
#    - name: Mask API Key
#      shell: bash
#      run: |
#        echo "::add-mask::"${{ inputs.apiKey }}""

    - name: Set local.properties
      shell: bash
      env:
        API_KEY: ${{ inputs.API_KEY }}
      run: echo "apiKey=${{env.API_KEY}}" >> ./local.properties
        
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
        cache: gradle

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3