runs:
  using: composite
  steps:
    # ローカルプロパティの設定
    - name: Set local.properties
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        echo "apiKey=$API_KEY" >> ./local.properties

    # JDKセットアップ
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
        cache: gradle

    # Gradleセットアップ
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3