[versions]
accompanist = "0.30.1"
androidGradlePlugin = "8.1.0-rc01"
androidxAppCompat = "1.7.0-alpha02"
androidxCompose = "1.4.3"
androidxComposeMaterial3 = "1.2.0-alpha02"
androidxCore = "1.10.1"
androidxCoreSplashscreen = "1.0.1"
androidxDataStore = "1.0.0"
androidxCoroutines = "1.7.2"
androidxHilt = "1.0.0"
androidxNavigation = "2.6.0"
androidxTestCore = "1.5.0"
androidxUi = "1.5.0-beta03"
constraintlayout = "2.1.4"
dokka = "1.8.20"
firebaseBom = "32.1.1"
firebaseCrashlyticsPlugin = "2.9.6"
gmsPlugin = "4.3.15"
hilt = "2.46.1"
junit4 = "4.13.2"
kotlin = "1.8.20"
kotlinxSerializationJson = "1.5.1"
ksp = "1.8.20-1.0.11"
ktlint = "0.50.0"
ossLicenses = "17.0.1"
ossLicensesPlugin = "0.10.6"
robolectric = "4.10.3"
room = "2.5.2"
secrets = "2.0.1"
timber = "5.0.1"
truth = "1.1.5"
playAppUpdate = "2.1.0"
playReview = "2.0.1"

# ** I'm using it, so no deletions allowed. **
androidxComposeCompiler = "1.4.6"

[libraries]
# Accompanist
accompanist-systemuicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist" }
accompanist-webView = { group = "com.google.accompanist", name = "accompanist-webview", version.ref = "accompanist" }

# Androidx
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppCompat" }
androidx-compose-animation-graphics= { group = "androidx.compose.animation", name = "animation-graphics", version.ref = "androidxCompose" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "androidxComposeMaterial3" }
androidx-compose-material3-windowSizeClass = { group = "androidx.compose.material3", name = "material3-window-size-class", version.ref = "androidxComposeMaterial3" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "androidxUi" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "androidxUi" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "androidxUi" }
androidx-compose-ui-viewbinding = { group = "androidx.compose.ui", name = "ui-viewbinding", version.ref = "androidxUi" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidxCoreSplashscreen" }
androidx-dataStore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "androidxDataStore" }
androidx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "androidxCoroutines" }
androidx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "androidxCoroutines" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxNavigation" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "androidxTestCore" }

# JUnit
junit = { group = "junit", name = "junit", version.ref = "junit4" }

# kotlinx-serialization
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }

# Play Services
play-app-update = { group = "com.google.android.play", name = "app-update", version.ref = "playAppUpdate" }
play-app-update-ktx = { group = "com.google.android.play", name = "app-update-ktx", version.ref = "playAppUpdate" }
play-oss-licenses = { group = "com.google.android.gms", name = "play-services-oss-licenses", version.ref = "ossLicenses" }
play-review = { group = "com.google.android.play", name = "review", version.ref = "playReview" }

# Ktlint
ktlint = { group = "com.pinterest", name = "ktlint", version.ref = "ktlint" }

# Robolectric
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }

# Hilt
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidxHilt" }

# Truth
truth = { group = "com.google.truth", name = "truth", version.ref = "truth" }

# Timber
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }

# Firebase
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref="firebaseBom"}
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics-ktx"}
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics-ktx"}

# Room
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
gms = { id = "com.google.gms.google-services", version.ref = "gmsPlugin"}
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin"}
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
oss-licenses = { id = "com.google.android.gms.oss-licenses-plugin", version.ref = "ossLicensesPlugin" }
secrets = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "secrets" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlyticsPlugin"}
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
