name: Dependencies

on:
  pull_request:
    paths-ignore:
      - README.md

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          api-key: ${{ secrets.API_KEY }}
