name: SaveScreenshot

on:
  pull_request:
    types:
      - closed

jobs:
  save-screenshot:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          api-key: ${{ secrets.API_KEY }}

      - name: create screenshots
        run: ./gradlew recordRoborazziProdDebug --stacktrace

      - uses: actions/upload-artifact@v3
        with:
          name: screenshot
          path: |
            **/build/outputs/roborazzi
          retention-days: 30