name: SaveScreenshot

on:
  pull_request:
    types:
      - closed
    paths-ignore:
      - README.md

jobs:
  save-screenshot:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          api-key: ${{ secrets.API_KEY }}

      - name: create screenshots
        run: ./gradlew recordRoborazziProdDebug --stacktrace

      - name: Save SAVE_NAME
        run: echo "SAVE_NAME=$( echo screenshot-${{ github.head_ref }} | sed "s/\//-/g" )" >> $GITHUB_ENV

      - name: Save screenshots
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.SAVE_NAME }}
          path: |
            **/build/outputs/roborazzi/
          retention-days: 30