name: Test

on:
  pull_request:
    branches:
      - main
      - develop
      - feature/*
    paths-ignore:
      - README.md

permissions:
  contents: read
  actions: read

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          api-key: ${{ secrets.API_KEY }}

      - name: Slack notify
        uses: ./.github/actions/incoming-webhook
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}

  test-prod:
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          api_key: ${{ secrets.API_KEY }}

      - name: ktlint-check
        run: ./gradlew --continue ktlintCheck

      - name: Test ProdDebug
        run: ./gradlew testProdDebugUnitTest

      - name: Report jacoco
        run: ./gradlew jacocoTestReport

      - name: jacoco-report to zip
        run: zip -r jacocoTestReport.zip ./build/reports/jacoco/jacocoTestReport/html

      - name: Archive jacoco report
        uses: actions/upload-artifact@v4
        with:
          name: jacocoTestReport
          path: ./build/reports/jacoco/jacocoTestReport/html

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - name: Danger
        uses: MeilCli/danger-action@v5
        with:
          plugins_file: Gemfile
          install_path: vendor/bundle
          danger_file: Dangerfile
          danger_id: danger-pr
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}

  compile-mock:
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          api_key: ${{ secrets.API_KEY }}

      - name: Compile MockDebug
        run: ./gradlew compileMockDebugSource
